# @format

name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create service account key file
        run: |
          mkdir -p functions
          echo "$GCP_SERVICE_ACCOUNT_JSON" > functions/google-service-account.json
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      # 이후에 이 파일을 사용하는 예:
      - name: Use GCP Key
        run: |
          cat functions/google-service-account.json
